version: "3"

services:
  delayed:
    build: .
    command: ./app
    container_name: delayed_notifier
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_MASTER_DSN=postgres://postgres:postgres@postgres:5432/mydb?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=password
      - RABBIT_URL=amqp://myuser:mypassword@rabbitmq:5672/

    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: delayed_pg
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ${PG_DATA_DIR:-./pg_data}:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: delayed_redis
    command: redis-server --requirepass password --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - ${REDIS_DATA_DIR:-./redis_data}:/data
    networks:
      - app-network

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: delayed_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    volumes:
      - ${RABBITMQ_DATA_DIR:-./rabbitmq_data}:/data
    networks:
      - app-network

networks:
  app-network:
