version: '3.8'

services:

  db:
    image: postgres:18-alpine
    container_name: postgres_delayed
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delNotifier
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq_delayed
    environment:
      - RABBITMQ_DEFAULT_USER: admin
      - RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq

  # веб-интерфейс для postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
